using EasyModelAnalysis, SciMLTesting, Test

# The modeling stack EasyModelAnalysis deliberately reexports, so that
# `using EasyModelAnalysis` on its own is enough to build a model, solve it, sample a
# parameter distribution and plot the result. Kept in sync with the reexport `export`
# blocks in src/EasyModelAnalysis.jl. Every name here is owned, documented and rendered
# by its upstream package (DifferentialEquations, ModelingToolkit, Distributions or
# Plots), so the public-API docstring and rendering checks skip them as well.
const REEXPORTS = (
    Symbol("@P_str"), Symbol("@acrule"), Symbol("@animate"), Symbol("@arrayop"),
    Symbol("@brownian"), Symbol("@brownians"), Symbol("@colorant_str"),
    Symbol("@component"), Symbol("@connector"), Symbol("@constants"),
    Symbol("@derivative_rule"), Symbol("@derivatives"), Symbol("@discretes"),
    Symbol("@gif"), Symbol("@independent_variables"), Symbol("@layout"),
    Symbol("@makearray"), Symbol("@mtkbuild"), Symbol("@mtkcompile"),
    Symbol("@mtkcomplete"), Symbol("@named"), Symbol("@namespace"), Symbol("@nonamespace"),
    Symbol("@pack!"), Symbol("@parameters"), Symbol("@poissonians"), Symbol("@recipe"),
    Symbol("@register_array_symbolic"), Symbol("@register_derivative"),
    Symbol("@register_discontinuity"), Symbol("@register_inverse"),
    Symbol("@register_symbolic"), Symbol("@rule"), Symbol("@series"), Symbol("@shorthands"),
    Symbol("@symbolic_wrap"), Symbol("@syms"), Symbol("@symstruct"), Symbol("@unpack"),
    Symbol("@userplot"), Symbol("@variables"), Symbol("@wrapped"), :ABGR, :ADIN99, :ADIN99d,
    :ADIN99o, :AGray, :AGray32, :AHSI, :AHSL, :AHSV, :ALCHab, :ALCHuv, :ALMS, :ALab, :ALuv,
    :AOklab, :AOklch, :ARGB, :ARGB32, :AXYZ, :AYCbCr, :AYIQ, :AbstractAGray, :AbstractARGB,
    :AbstractAnalyticalProblem, :AbstractBackend, :AbstractCollocation,
    :AbstractDynamicOptProblem, :AbstractGray, :AbstractGrayA, :AbstractLayout,
    :AbstractMixtureModel, :AbstractMvNormal, :AbstractNonlinearProblem, :AbstractPlot,
    :AbstractRGB, :AbstractRGBA, :AddVector, :AffineOperator, :AllObserved, :AlphaColor,
    :AnalysisPoint, :AnalyticalProblem, :Animation, :Arcsine, :ArrayLikeVariate,
    :AssignmentAffect, :AutoDePSpecialize, :AutoFiniteDiff, :AutoForwardDiff, :AutoSparse,
    :AutoTsit5, :AutoVern6, :AutoVern7, :AutoVern8, :AutoVern9, :AxyY, :BGR, :BGRA, :BS,
    :BVPFunction, :BVProblem, :BatchIntegralFunction, :Bernoulli, :BernoulliLogit, :Beta,
    :BetaBinomial, :BetaPrime, :BezierCurve, :Binomial, :BipartiteGraph, :Biweight,
    :BlockDiagonalOperator, :CIE1931JV_CMF, :CIE1931J_CMF, :CIE1931_CMF, :CIE1964_CMF,
    :CIE2006_10_CMF, :CIE2006_2_CMF, :CallbackSet, :CasADiCollocation,
    :CasADiDynamicOptProblem, :Categorical, :Cauchy, :CheckInit, :Chernoff, :Chi, :Chisq,
    :CholeskyVariate, :Clock, :Clocks, :Color, :Color3, :ColorAlpha, :ColorGradient,
    :ColorPalette, :ColorTypes, :Colorant, :ColorantNormed, :Colors, :CompilerOptions,
    :Connection, :Continuous, :ContinuousCallback, :ContinuousDistribution,
    :ContinuousMatrixDistribution, :ContinuousMultivariateDistribution,
    :ContinuousUnivariateDistribution, :ConvexOptimizationProblem, :Cosine, :DAEFunction,
    :DAEProblem, :DAESolution, :DDEFunction, :DDEProblem, :DE_2000, :DE_94, :DE_AB, :DE_BFD,
    :DE_CMC, :DE_DIN99, :DE_DIN99d, :DE_DIN99o, :DE_JPC79, :DIN99, :DIN99A, :DIN99d,
    :DIN99dA, :DIN99o, :DIN99oA, :DefaultODEAlgorithm, :DiagNormal, :DiagNormalCanon,
    :DiagonalOperator, :Differential, :DifferentialEquations, :Dirac, :Dirichlet,
    :DirichletMultinomial, :Discrete, :DiscreteCallback, :DiscreteDistribution,
    :DiscreteFunction, :DiscreteMatrixDistribution, :DiscreteMultivariateDistribution,
    :DiscreteNonParametric, :DiscreteProblem, :DiscreteSystem, :DiscreteUniform,
    :DiscreteUnivariateDistribution, :Distribution, :Distributions, :DoubleExponential,
    :DynamicOptSolution, :DynamicalBVPFunction, :DynamicalDDEFunction, :DynamicalDDEProblem,
    :DynamicalODEFunction, :DynamicalODEProblem, :DynamicalSDEFunction,
    :DynamicalSDEProblem, :EdgeworthMean, :EdgeworthSum, :EdgeworthZ, :EigenvalueProblem,
    :EigenvalueSolution, :EigenvalueTarget, :EnsembleAnalysis, :EnsembleContext,
    :EnsembleDistributed, :EnsembleProblem, :EnsembleSerial, :EnsembleSolution,
    :EnsembleSplitThreads, :EnsembleSummary, :EnsembleTestSolution, :EnsembleThreads,
    :Epanechnikov, :Equation, :Erlang, :Estimator, :EvalAt, :Exponential, :FBDF, :FDist,
    :FisherNoncentralHypergeometric, :Flow, :Formatted, :Fractional, :Frechet, :FullNormal,
    :FullNormalCanon, :FunctionOperator, :GR, :Gamma, :GeneralizedExtremeValue,
    :GeneralizedPareto, :Geometric, :Girsanov_transform, :GlobalScope, :Gray, :Gray24,
    :GrayA, :Gumbel, :HSB, :HSI, :HSIA, :HSL, :HSLA, :HSV, :HSVA, :Hold,
    :HomotopyContinuationProblem, :HomotopyNonlinearFunction, :HomotopyProblem,
    :Hypergeometric, :IRStructure, :IdentityOperator, :ImplicitDiscreteFunction,
    :ImplicitDiscreteProblem, :ImplicitDiscreteSystem, :IncrementingODEFunction,
    :IncrementingODEProblem, :Inequality, :InfiniteOptCollocation,
    :InfiniteOptDynamicOptProblem, :Initial, :InitializationProblem, :Integral,
    :IntegralFunction, :IntegralProblem, :IntegralSolution, :IntervalNonlinearFunction,
    :IntervalNonlinearProblem, :InverseGamma, :InverseGaussian, :InverseWishart,
    :InvertibleOperator, :IsoNormal, :IsoNormalCanon, :JohnsonSU, :JointOrderStatistics,
    :JuMPCollocation, :JuMPDynamicOptProblem, :JumpProblem, :JumpSystem, :KSDist,
    :KSOneSided, :KW, :Kolmogorov, :Kumaraswamy, :LCHab, :LCHabA, :LCHuv, :LCHuvA, :LKJ,
    :LKJCholesky, :LMS, :LMSA, :Lab, :LabA, :Laplace, :Levy, :Lindley,
    :LinearAliasSpecifier, :LinearProblem, :LinearSolution, :LinearizationOpPoint,
    :LinearizationProblem, :LocalScope, :LocationScale, :LogLogistic, :LogNormal,
    :LogUniform, :Logistic, :LogitNormal, :Luv, :LuvA, :MLEstimator, :MSC, :MTKParameters,
    :MatrixBeta, :MatrixDistribution, :MatrixFDist, :MatrixNormal, :MatrixOperator,
    :MatrixReshaped, :MatrixTDist, :Matrixvariate, :MiscSystemData, :MissingGuessValue,
    :MixtureModel, :ModelingToolkit, :ModelingToolkitBase,
    :MultiObjectiveOptimizationFunction, :Multinomial, :Multivariate,
    :MultivariateDistribution, :MultivariateMixture, :MultivariateNormal, :MvLogNormal,
    :MvLogitNormal, :MvNormal, :MvNormalCanon, :MvNormalKnownCov, :MvTDist,
    :NamedTupleVariate, :NegativeBinomial, :NoiseProblem, :NonMatrixDistribution,
    :NoncentralBeta, :NoncentralChisq, :NoncentralF, :NoncentralHypergeometric,
    :NoncentralT, :NonlinearFunction, :NonlinearLeastSquaresProblem, :NonlinearProblem,
    :NonlinearSolution, :NonlinearSystem, :Normal, :NormalCanon, :NormalInverseGaussian,
    :NullOperator, :Num, :ODEAliasSpecifier, :ODEFunction, :ODEInputFunction, :ODEProblem,
    :ODESolution, :ODESystem, :OHLC, :Oklab, :OklabA, :Oklch, :OklchA,
    :OptimizationFunction, :OptimizationProblem, :OptimizationSolution, :OptimizationSystem,
    :OrderStatistic, :OrdinaryDiffEq, :PDENoTimeSolution, :PDEProblem, :PDESystem,
    :PDETimeSeriesSolution, :PGeneralizedGaussian, :ParentScope, :Pareto, :PlotTheme,
    :PlotThemes, :PlotUtils, :Plots, :Poisson, :PoissonBinomial, :Pre, :Product,
    :PyomoCollocation, :PyomoDynamicOptProblem, :QQPair, :RGB, :RGB24, :RGBA, :RGBX,
    :RODEFunction, :RODEProblem, :RODESolution, :Rayleigh, :RealInterval, :RecipeData,
    :RecipesBase, :ReturnCode, :Rewriters, :Rician, :Rodas5P, :Rosenbrock23, :RuleSet,
    :SCCNonlinearProblem, :SDDEFunction, :SDDEProblem, :SDEFunction, :SDEProblem,
    :SDESystem, :SafeReal, :Sample, :SampleTime, :Sampleable, :SampledIntegralProblem,
    :ScalarOperator, :SciMLBase, :SciMLLogging, :SciMLOperators, :SecondOrderBVProblem,
    :SecondOrderDDEProblem, :SecondOrderODEProblem, :Segments, :Semicircle,
    :SemilinearODEFunction, :SemilinearODEProblem, :Shape, :Shift, :ShiftIndex, :Skellam,
    :SkewNormal, :SkewedExponentialPower, :Soliton, :SolverStepClock, :SplitFunction,
    :SplitODEProblem, :SplitSDEFunction, :SplitSDEProblem, :StaticWOperator,
    :SteadyStateProblem, :SteadyStateSolution, :Stream, :StructuralTransformations,
    :StudentizedRange, :SufficientStats, :Surface, :SymReal, :SymScope, :SymStruct,
    :SymTriangularDist, :SymbolicLinearODE, :SymbolicMassActionJump, :SymbolicUtils,
    :Symbolics, :SymbolicsSparsityDetector, :System, :TDist, :TearingState,
    :TensorProductOperator, :TensorSumOperator, :Term, :TimeDomain, :Transparent3,
    :TransparentColor, :TransparentGray, :TransparentRGB, :TreeReal, :TriangularDist,
    :Triweight, :Truncated, :Tsit5, :TwoPointBVPFunction, :TwoPointBVProblem,
    :TwoPointDynamicalBVPFunction, :TwoPointSecondOrderBVProblem, :UnPack, :Uniform,
    :Univariate, :UnivariateDistribution, :UnivariateGMM, :UnivariateMixture, :ValueSupport,
    :VariateForm, :VectorContinuousCallback, :Vern6, :Vern7, :Vern8, :Vern9, :VonMises,
    :VonMisesFisher, :WOperator, :WalleniusNoncentralHypergeometric, :Weibull, :Wishart,
    :XRGB, :XYZ, :XYZA, :YCbCr, :YCbCrA, :YIQ, :YIQA, :ZeroMeanDiagNormal,
    :ZeroMeanDiagNormalCanon, :ZeroMeanFullNormal, :ZeroMeanFullNormalCanon,
    :ZeroMeanIsoNormal, :ZeroMeanIsoNormalCanon, :adapted_grid, :add_accumulations,
    :add_saveat!, :add_theme, :add_tstop!, :addat!, :addat_non_user_cache!, :addsteps!,
    :alg_equations, :alias_elimination, :aliases, :alpha, :alphacolor,
    :analytically_integrated, :analyze_initialization_jacobian, :animate, :annotate!,
    :approximation_function, :areaplot, :areaplot!, :arguments, :arrow, :asdigraph,
    :asgraph, :attr!, :auto_dt_reset!, :backend, :backend_name, :backend_object, :backends,
    :bar, :bar!, :barh, :barh!, :barhist, :barhist!, :base_color_type, :base_colorant_type,
    :bbox, :bindings, :blue, :bound_parameters, :boxplot, :boxplot!, :brownians, :brush,
    :build_function, :but_ordered_incidence, :cache_operator, :calculate_control_jacobian,
    :calculate_cost_gradient, :calculate_cost_hessian, :calculate_hessian,
    :calculate_jacobian, :calculate_massmatrix, :calculate_tgrad, :canonform, :ccdf,
    :ccolor, :cdf, :censored, :center, :cf, :cgf, :cgrad, :change_independent_variable,
    :change_of_variables, :change_t_via_interpolation!, :check_error, :check_keywords,
    :chroma, :cie_color_match, :circvar, :closeall, :color, :color_list, :color_type,
    :coloralpha, :colordiff, :colormap, :colormatch, :comp1, :comp2, :comp3, :comp4, :comp5,
    :complete, :component, :components, :componentwise_logpdf, :componentwise_pdf, :compose,
    :concentration, :concretize, :connect, :constraints, :continuous_events, :contour,
    :contour!, :contour3d, :contour3d!, :contourf, :contourf!, :convert_system_indepvar,
    :convolve, :coords, :cor, :cost, :cov, :cquantile, :current, :curve_points, :curves,
    :curves!, :cvec, :dae_index_lowering, :debug_system, :default, :default_cgrad,
    :deleteat!, :deleteat_non_user_cache!, :density, :density!, :derivative_discontinuity!,
    :deuteranopic, :diff_equations, :dim, :discrete_events, :discretize,
    :distinguishable_colors, :diverging_palette, :dof, :domain_connect, :du_cache,
    :dummy_derivative, :entropy, :eqeq_dependencies, :equation_dependencies, :equations,
    :estimate, :expand, :expand_connections, :expand_derivatives, :expected_logdet, :extend,
    :factors, :failprob, :find_solvables!, :first_tstop, :fit, :fit_mle, :flatten,
    :flatten_fractions, :font, :fractional_to_ordinary, :frame, :full_cache,
    :full_equations, :gamutmax, :gamutmin, :gaston, :gather_factor, :generate_W,
    :generate_control_jacobian, :generate_cost, :generate_cost_gradient,
    :generate_cost_hessian, :generate_custom_function, :generate_diffusion_function,
    :generate_initializesystem, :generate_jacobian, :generate_rhs, :generate_tgrad,
    :get_alg_eqs, :get_canonical_expr, :get_color_palette, :get_comp_sensitivity,
    :get_comp_sensitivity_function, :get_diff_eqs, :get_dt, :get_du, :get_du!,
    :get_looptransfer, :get_looptransfer_function, :get_proposed_dt, :get_reachability,
    :get_rng, :get_sensitivity_function, :get_tmp_cache, :get_variables, :getbounds,
    :getconnect, :getdescription, :getdist, :getguess, :getmetadata, :getmisc, :getnominal,
    :getunit, :gif, :gr, :gradlogpdf, :gray, :green, :grid, :groebner_basis, :guesses, :gui,
    :has_adjoint, :has_alg_eqs, :has_alg_equations, :has_concretization, :has_diff_eqs,
    :has_diff_equations, :has_exp, :has_expmv, :has_expmv!, :has_inverse, :has_ldiv,
    :has_ldiv!, :has_left_inverse, :has_mul, :has_mul!, :has_right_inverse, :has_rng,
    :has_tstop, :hasbounds, :hasconnect, :hasdescription, :hasdist, :hasfinitesupport,
    :hasguess, :hasmetadata, :hasmisc, :hasnominal, :hasunit, :hdf5, :heatmap, :heatmap!,
    :hex, :hexbin, :hexbin!, :hierarchy, :highest_order_variable_mask, :histogram,
    :histogram!, :histogram2d, :histogram2d!, :hline, :hline!, :homotopy, :hspan, :hspan!,
    :hue, :ifelse_branching, :ifelse_eager, :independent_variable, :independent_variables,
    :infimum, :init, :initial_conditions, :initialization_equations, :inline, :inspectdr,
    :instream, :insupport, :invcov, :inverse, :invisible, :invlogccdf, :invlogcdf,
    :invscale, :irreducibles, :is_derivative, :is_discrete_time_domain, :is_groebner_basis,
    :isbounded, :iscached, :iscall, :isclock, :isconstant, :iscontinuous, :isconvertible,
    :isdark, :isdiscrete, :isdisturbance, :isinitial, :isinplace, :isinput, :isirreducible,
    :isleptokurtic, :islinear, :islowerbounded, :ismesokurtic, :isolate_subsystem,
    :isoutput, :isplatykurtic, :isprobvec, :issolverstepclock, :issquare, :istree,
    :istunable, :isupperbounded, :iter_segments, :jumps, :kldivergence, :kronsum, :kurtosis,
    :left_continuous_function, :left_inverse, :lens!, :limit,
    :linear_fractional_to_ordinary, :linearization_ap_transform, :linearization_function,
    :linearize, :liouville_transform, :location, :location!, :logccdf, :logcdf, :logdetcov,
    :logdiffcdf, :loglikelihood, :logpdf, :logpdf!, :lowest_order_variable_mask,
    :majorization_function, :map_variables_to_equations, :mapc, :mapreducec, :maybe_zeros,
    :mean, :mean_hue, :meandir, :meanform, :meanlogx, :median, :mesh3d, :mesh3d!, :mgf,
    :minorization_function, :mode, :modelingtoolkitize, :modes, :moment, :mov, :mp4,
    :mtkcompile, :mtkcompile!, :ncategories, :ncomponents, :noise_to_brownians,
    :normalize_hue, :nsamples, :ntrials, :observables, :observed, :ohlc, :ohlc!, :open_loop,
    :operation, :optimize_datetime_ticks, :optimize_ticks, :palette, :pantelides_reassemble,
    :parameters, :parametric_colorant, :params, :params!, :parse_expr_to_symbolic, :partype,
    :path3d, :path3d!, :pdf, :pdfsquaredL2norm, :pgfplots, :pgfplotsx, :pie, :pie!, :plot,
    :plot!, :plot3d, :plot3d!, :plot_color, :plotarea, :plotattr, :plotly, :plotlyjs,
    :plots_heatmap, :plots_heatmap!, :png, :polynomial_coeffs, :pop_tstop!, :populate_ir!,
    :portfoliocomposition, :portfoliocomposition!, :print_ir, :probs, :probval,
    :product_distribution, :protanopic, :pyplot, :pythonplot, :qqbuild, :quantile,
    :quick_cancel, :quiver, :quiver!, :rand_cache, :rate, :ratenoise_cache, :red, :reducec,
    :reeval_internals_due_to_modification!, :reinit!, :remake,
    :reorder_dimension_by_tunables, :reorder_dimension_by_tunables!, :resetfontsizes,
    :resize_non_user_cache!, :respecialize, :rgb_string, :rgba_string,
    :right_continuous_function, :right_inverse, :rootfunction, :rotate, :rotate!, :sample,
    :sample!, :sampler, :savefig, :savevalues!, :scale, :scale!, :scalefontsize,
    :scalefontsizes, :scatter, :scatter!, :scatter3d, :scatter3d!, :scatterhist,
    :scatterhist!, :semilinear_form, :semipolynomial_form, :semiquadratic_form,
    :sequential_palette, :series, :set_abstol!, :set_defaults, :set_proposed_dt!,
    :set_reltol!, :set_rng!, :set_t!, :set_theme, :set_u!, :setmetadata, :setnominal,
    :shape, :shape_coords, :showtheme, :showtheme!, :simplify, :simplify_fractions,
    :skewness, :solve, :solve!, :solve_for, :solve_linear_ode_system, :solve_symbolic_IVP,
    :sorted_arguments, :sorted_incidence_matrix, :span, :spy, :spy!, :sqmahal, :sqmahal!,
    :state_priorities, :state_priority, :std, :stdlogx, :step!, :stephist, :stephist!,
    :sticks, :sticks!, :stochastic_integral_transform, :stroke, :structural_simplify,
    :subset_tunables, :substitute, :substitute_component, :substitute_in_deriv,
    :substitute_in_deriv_and_depvar, :successful_retcode, :succprob, :suffstats, :support,
    :supports_solve_rng, :supremum, :surface, :surface!, :symbolic_discretize,
    :symbolic_linear_solve, :symbolic_solve, :symbolic_solve_ode, :symbolics_to_sympy,
    :symbolics_to_sympy_pythoncall, :sympy_algebraic_solve, :sympy_integrate, :sympy_limit,
    :sympy_linear_solve, :sympy_ode_solve, :sympy_pythoncall_algebraic_solve,
    :sympy_pythoncall_integrate, :sympy_pythoncall_limit, :sympy_pythoncall_linear_solve,
    :sympy_pythoncall_ode_solve, :sympy_pythoncall_simplify, :sympy_pythoncall_to_symbolics,
    :sympy_simplify, :sympy_to_symbolics, :taylor, :taylor_coeff, :tearing,
    :tearing_substitution, :term, :terminate!, :terms, :test_examples, :text, :theme,
    :theme_palette, :title!, :toexpr, :toggle_namespacing, :tosymbol, :translate,
    :translate!, :tritanopic, :truncated, :tunable_parameters, :twinx, :twiny, :u_cache,
    :u_modified!, :unicodeplots, :unknowns, :unwrap_const, :update_coefficients,
    :update_coefficients!, :user_cache, :var, :variable_dependencies, :varlogx, :vartype,
    :varvar_dependencies, :violin, :violin!, :vline, :vline!, :vspan, :vspan!, :warn_compat,
    :webm, :weighted_color_mean, :whitebalance, :wireframe, :wireframe!, :with, :wrap,
    :wsample, :wsample!, :xaxis!, :xerror, :xerror!, :xflip!, :xgrid!, :xlabel!, :xlims,
    :xlims!, :xticks, :xticks!, :xyY, :xyYA, :yaxis!, :yerror, :yerror!, :yflip!, :ygrid!,
    :ylabel!, :ylims, :ylims!, :yticks, :yticks!, :zaxis!, :zerror, :zerror!, :zflip!,
    :zgrid!, :zlabel!, :zlims, :zlims!, :zscale, :zticks, :zticks!, Symbol("≲"),
    Symbol("≳"),
)

run_qa(
    EasyModelAnalysis;
    reexports_allow = REEXPORTS,
    api_docs_kwargs = (; ignore = REEXPORTS, rendered_ignore = REEXPORTS),
    # The reexported names are brought into scope by the bare `using` of each upstream
    # package in src/EasyModelAnalysis.jl; they are reexported, not used, so they are not
    # implicit imports that should be made explicit.
    ei_kwargs = (; no_implicit_imports = (; ignore = REEXPORTS)),
)

@testset "Reexport surface" begin
    # Every approved reexport must actually be reachable from `using EasyModelAnalysis`,
    # so the allow-list cannot drift into approving names the package no longer provides.
    unreachable = filter(
        name -> !(
            Base.ispublic(EasyModelAnalysis, name) &&
                isdefined(EasyModelAnalysis, name)
        ),
        collect(REEXPORTS),
    )
    @test isempty(unreachable)
end
